version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    target-branch: "main"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: "-"
    reviewers:
      - "dbrajovic"
      - "zivkovicmilos"