---
name: Lint
on:  # yamllint disable-line rule:truthy
  push:
    tags-ignore:
      - 'v*'
    paths:
      - '**.go'
  workflow_call:
  pull_request:

jobs:
  lint:
    name: Linters
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21.x

      - name: Checkout code
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: '0'

      - name: fetch main
        run: git fetch origin main && git branch main remotes/origin/main

      - name: Lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: latest
          args:
            --config=./.golangci.yml

      - name: Static check
        uses: dominikh/staticcheck-action@v1
        with:
          version: "latest"
          install-go: false
